### ISSUE TITLE
preparation for integration with inborutils

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/inbomisc#4]
@pietervsd, as discussed earlier, I transferred the [inborutils](https://github.com/inbo/inborutils) towards a package and I'm now ready to port the functionalities from `inbomisc` as well. However, I do think it is best to have some overview to get this as smooth as possible. 

When I check the `NAMESPACE`, I see following functionalities:

* [ ] `export(Zuur_MultiVariogram)` and `export(Zuur_Variogram)`: I think these can be easily transferred with taking into account a bit of syntax alignments.
* [ ] `export(qd_pci1)`, `export(qd_pci2)` and `export(qd_pci2_D)` + export(qd_profile): Could we agree on more descriptive function names to clarify the user the purpose of the functions. Besides, I think it would be useful to have a vignette to explain these functionalities, do you have such a thing available.
*  [ ] `export(vif)`: checking the file `modelbouw_variance_inflation.R`, this lacks a lot of roxygen documentation and it is not completely clear how this relates to e.g. the `car::vif` functions? Could you clarify a bit more?

Furthermore, I' ve found functions in the `R` directory:
* [ ] `texSanitize.fct`, `itemizeNest.fct`, `texItemizeCompose.fct`, `texItemize.fct`: these Tex manipulation functionalities. I assume the `qever_**` naming is not required, as this is a general utility to interact with Tex code?
* [ ] `pop.projection.AR`: Seems directly portable, apart from the imports and maybe an alterrnative function name (e.g. with underscores)?

We can keep track of the transfer by marking the ported functions (with an x). If you think any of these should just not be ported (as too specific and part of an other project), just mark it already (as if already done). 

What's your idea about how to do the transfer?

**Comment by pietervsd** [comment]
All functions and corresponding scripts of the inbomisc iteration of the package can be deleted

**Comment by pietervsd** [comment]
Repository is ready for deletion

**Comment by peterdesmet** [comment]
Will do!
